create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'Administrador'
  );
$$;

alter table public.products
  add column if not exists collection_id integer null,
  add column if not exists sell_individually boolean not null default true;

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  name text not null,
  subtitle text not null default '',
  image text not null default '',
  color text not null default '#ff2d95',
  created_at timestamptz not null default now()
);

alter table public.collections
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists price numeric not null default 0,
  add column if not exists discount_percent numeric not null default 0,
  add column if not exists active boolean not null default true,
  add column if not exists product_ids integer[] not null default '{}';

create table if not exists public.product_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.product_styles (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.product_colors (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  hex text not null default '#ff2d95',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.collections enable row level security;
alter table public.product_categories enable row level security;
alter table public.product_styles enable row level security;
alter table public.product_colors enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'collections' and policyname = 'Public can read active collections') then
    create policy "Public can read active collections"
      on public.collections for select
      using (active = true or public.is_admin());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'collections' and policyname = 'Admins can manage collections') then
    create policy "Admins can manage collections"
      on public.collections for all
      using (public.is_admin())
      with check (public.is_admin());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'product_categories' and policyname = 'Public can read categories') then
    create policy "Public can read categories"
      on public.product_categories for select
      using (active = true or public.is_admin());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'product_categories' and policyname = 'Admins can manage categories') then
    create policy "Admins can manage categories"
      on public.product_categories for all
      using (public.is_admin())
      with check (public.is_admin());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'product_styles' and policyname = 'Public can read styles') then
    create policy "Public can read styles"
      on public.product_styles for select
      using (active = true or public.is_admin());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'product_styles' and policyname = 'Admins can manage styles') then
    create policy "Admins can manage styles"
      on public.product_styles for all
      using (public.is_admin())
      with check (public.is_admin());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'product_colors' and policyname = 'Public can read colors') then
    create policy "Public can read colors"
      on public.product_colors for select
      using (active = true or public.is_admin());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'product_colors' and policyname = 'Admins can manage colors') then
    create policy "Admins can manage colors"
      on public.product_colors for all
      using (public.is_admin())
      with check (public.is_admin());
  end if;
end $$;

insert into public.product_categories (name, slug)
values
  ('Cabelos', 'cabelos'),
  ('Roupas', 'roupas'),
  ('Acessorios', 'acessorios'),
  ('Conjuntos', 'conjuntos'),
  ('Outros', 'outros')
on conflict (slug) do nothing;

insert into public.product_styles (name, slug)
values
  ('Gotica', 'gotica'),
  ('Soft', 'soft'),
  ('Neon', 'neon'),
  ('Street', 'street'),
  ('Y2K', 'y2k'),
  ('Grunge', 'grunge')
on conflict (slug) do nothing;

insert into public.product_colors (name, slug, hex)
values
  ('Rosa', 'rosa', '#ff2d95'),
  ('Roxo', 'roxo', '#b347d9'),
  ('Preto', 'preto', '#1a1a1a'),
  ('Branco', 'branco', '#f0f0f0'),
  ('Vermelho', 'vermelho', '#ff4444'),
  ('Azul', 'azul', '#4488ff'),
  ('Verde', 'verde', '#44ff88'),
  ('Amarelo', 'amarelo', '#ffdd44'),
  ('Laranja', 'laranja', '#ff8844'),
  ('Cinza', 'cinza', '#888888')
on conflict (slug) do nothing;
